$script = <<SCRIPT
sudo apt-get install -qqy git
cd /home/vagrant
git clone https://github.com/maurizi/dotfiles.git
cd dotfiles
./scripts/ubuntu.sh
SCRIPT

Vagrant.configure("2") do |config|
  # Let me use ssh-agent with my host keys on the VM
  config.ssh.forward_agent = true

  # Clone the dotfiles repo and run the dotfiles configuration script

  config.vm.provision "shell", inline: $script, privileged: false
end
