#!/bin/bash

pathToView ()
{
    local path=$(readlink -f $1)
    if [[ $path =~ ^$HOME ]]
    then
        path=${path#$HOME}
        echo -n '~'
    fi
    echo "$(echo "$path" | sed 's/\//=+/g')="
}

for arg in $@
do
    rm ~/.vim/view/$(pathToView $arg)
done
