Vagrant.configure("2") do |config|
  # Let me use ssh-agent with my host keys on the VM

  # Share my home folder into the Vagrant VM
  config.vm.synced_folder "~/.dotfiles", "/home/vagrant/dotfiles"

  # Run the dotfiles configuration script
  config.vm.provision "shell", inline: "cd /home/vagrant/dotfiles && ./scripts/ubuntu.sh", privileged: false
end
